# Generated by Django 3.0.8 on 2020-07-05 21:04

import apps.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('brand', models.ForeignKey(on_delete=models.SET(apps.product.models.safe_remove), to='brand.Brand', verbose_name='Brand')),
            ],
        ),
    ]
