# Generated by Django 3.0.8 on 2020-07-05 21:29

import apps.service.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('status', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Serial number')),
                ('model_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Model number')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='Delivery date')),
                ('desc', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=models.SET(apps.service.models.safe_remove), related_name='product', to='product.Product', verbose_name='Product')),
                ('status', models.ForeignKey(on_delete=models.SET(apps.service.models.safe_remove), related_name='status', to='status.Status', verbose_name='Status')),
                ('user', models.ForeignKey(on_delete=models.SET(apps.service.models.safe_remove), related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
        ),
    ]
