# Generated by Django 3.0.8 on 2020-07-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='piece',
            old_name='amount',
            new_name='service_fee',
        ),
    ]
