# Generated by Django 3.0.8 on 2020-07-06 19:21

import apps.service.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_auto_20200706_1527'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='price',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='piece',
            old_name='service_fee',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='operation',
            name='service',
            field=models.ForeignKey(on_delete=models.SET(apps.service.models.safe_remove), related_name='operations', to='service.Service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='service',
            field=models.ForeignKey(on_delete=models.SET(apps.service.models.safe_remove), related_name='pieces', to='service.Service', verbose_name='Service'),
        ),
    ]
